### ISSUE TITLE
`one_timer` tasks are run multiple times

### ISSUE THREAD

**Issue by sandip-mane** [bigbinary/neeto_sso#63]
```ruby
namespace :one_timer do
  desc "test"
  task test: :environment do
    puts "hello"
  end
end
```

Output:
![image](https://user-images.githubusercontent.com/9862943/159221954-41354be8-ea5e-4525-93db-43a31a6c29f0.png)

### It's because the one timer tasks file is loaded multiple times.
https://github.com/bigbinary/neeto_sso/blob/03f403f844b86213a668442fadaf7e6c28fad9c6/lib/neeto_sso/railtie.rb#L7

**Comment by sandip-mane** [comment]
@ghousemohamed _a

**Comment by ghousemohamed** [comment]
@mustafapc19 _a
